name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel:
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP env using setup-php
      - uses: shivammathur/setup-php@2.27.1
        with:
          php-version: '8.1'
      - name: Copy .env
          run: php -r "file_exists('.env') || copy('.env.main', '.env');"
      - name: Install Dependencies
          run: composer install --ignore-platform-reqs -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Generate key
          run: php artisan key:generate
      - name: Directory Permissions
          run: chmod -R 755 storage bootstrap/cache public/uploads
      - name: Upload Directory Permission
          run: sudo chown -R www-data:www-data public/uploads storage bootstrap/cache
      - name: Deploy to DigitalOcean
          uses: appleboy/scp-action@v0.1.4
          with:
            host: ${{ secrets.MAIN_DROPLET_IP }}
            username: ${{ secrets.MAIN_DROPLET_USERNAME }}
            key: ${{ secrets.MAIN_DROPLET_PRIVATE_KEY }}
            source: ./*
            target: /var/www/html/laravel-playground/

      - name: Link Storage
        run: php artisan storage:link
      - name: Clear the cache
        run: php artisan optimize:clear
